[[obc]]
is_main_obc=true
c2a_root="./test_src/"
tlm_prefix="ISSL6U_MOBC_TLM_DB_"
tlm_dest_h="./test_src/telemetry_definitions.h"
tlm_dest_c="./test_src/telemetry_definitions.c"
tlm_src="./../tlm/ong_mobc/"
tlm_wings_dest="./../wings_data/tlm/"
cmd_dest_h="./test_src/command_definitions.h"
cmd_dest_c="./test_src/command_definitions.c"
cmd_src="./../cmd/ong_mobc.csv"
cmd_wings_dest="./../wings_data/cmd/ong_mobc.csv"
bct_dest="./test_src/block_command_definitions.h"
bct_src="./../bct/ong_mobc.csv"
bct_wings_dest="./../wings_data/bct/ong_mobc.csv"
db_prefix="ISSL6U_MOBC"
tlm_id_range=["0x00", "0x100"]

[[obc]]
is_main_obc=false
is_enable=true
name="AOBC"
db_prefix="ISSL6U_AOBC"
tlm_id_range=["0x00", "0xff"]
path_to_src="../test_src/"
path_to_db="../../tlm/ong_mobc/"
max_tlm_num=256
driver_path="Aocs/"
driver_type="AOBC_Driver"
driver_name="aobc_driver"
code_when_tlm_not_found="aobc_driver->info.comm.rx_err_code = AOBC_RX_ERR_CODE_TLM_NOT_FOUND;"
